In [7]:
import numpy as np

A = np.array([[1,3,2], [4,7,6]])
B = np.array([[2,8],[3,1],[5,9]])

C = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]

print ('Matriz A')
print(A)
print ('Matriz B')
print(B)
print ('Matriz C')
for linha in C:
  print(linha)


Matriz A
[[1 3 2]
 [4 7 6]]
Matriz B
[[2 8]
 [3 1]
 [5 9]]
Matriz C
[21, 29]
[59, 93]
